# This file is part of fdb-utils.
# https://github.com/cdecu/fdb-utils

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Carlos de Cumont <carlos@decumont.be>

language: python

python:
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
